language: rust

os:
  - linux
  - windows
  - osx

addons:
  apt:
    packages:
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libdbus-1-dev
  homebrew:
    update: true
    packages:
      - libusb

rust:
  - stable
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  cargo: true
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64
    - /C/Users/travis/.cargo/registry
    - /C/Users/travis/.cache/sccache
    - target

script:
  - cargo build --verbose --release
  - cargo build --verbose --release --features=notification
  - cargo build --verbose --release --features=encryption
  - cargo build --verbose --release --features=yubikey
  - cargo build --verbose --release --features=all
  - cargo test --features=all
  - cat ./.travis-merge.sh | env FLAGS="" bash
