language: rust

os:
  - linux
  - windows
  - osx

rust:
  - stable
  - nightly

jobs:
  allow_failures:
    - rust: nightly
    - os: osx
  fast_finish: true

cache: cargo

script:
  - cargo build --verbose --release
