[package]
name = "git-credential-keepassxc"
version = "0.1.0"
authors = ["Frederick Zhang <frederick888@tsundere.moe>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
crypto_box = "0.1.0"
base64 = "0.12.0"
rand = "0.7.3"
xdg = "2.2.0"
prctl = "1.0.0"
clap = "2.33.0"
slog = "2.5.2"
slog-term = "2.5.0"
anyhow = "1.0.28"
once_cell = "1.3.1"
